#!/usr/bin/env python3
"""Generate the single-file Skill bundles from the canonical source folders.

Bundles are build artifacts. Edit the Skill folders and rerun this script;
never edit a file under bundles/ directly.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BUNDLES: dict[str, dict[str, object]] = {
    "focal": {
        "title": "Focal",
        "summary": "The complete Focal Skill, including its `/12` audit rubric, patterns, and worked examples.",
        "files": [
            "focal/SKILL.md",
            "focal/reference/review.md",
            "focal/reference/patterns.md",
            "focal/reference/examples.md",
        ],
    },
    "compass": {
        "title": "Compass",
        "summary": "The complete Compass Skill, including its `/12` audit rubric, patterns, and worked examples.",
        "files": [
            "compass/SKILL.md",
            "compass/reference/review.md",
            "compass/reference/patterns.md",
            "compass/reference/examples.md",
        ],
    },
    "flywheel": {
        "title": "Flywheel",
        "summary": "The complete Flywheel Skill, including its complete-evidence `/16` and targeted `/4` audit contracts, four play references, and worked examples.",
        "files": [
            "flywheel/SKILL.md",
            "flywheel/reference/review.md",
            "flywheel/reference/trust.md",
            "flywheel/reference/friction.md",
            "flywheel/reference/wins.md",
            "flywheel/reference/emotion.md",
            "flywheel/reference/examples.md",
        ],
    },
    "soul": {
        "title": "Soul",
        "summary": "The complete Soul Skill, including its unscored Readiness check, `/12` audit rubric, moment and treatment references, and worked examples.",
        "files": [
            "soul/SKILL.md",
            "soul/reference/review.md",
            "soul/reference/moments.md",
            "soul/reference/treatments.md",
            "soul/reference/examples.md",
        ],
    },
    "product-judgement": {
        "title": "Product Judgement",
        "summary": "The Product Judgement orchestration Skill. For a holistic audit, load it with the four foundational bundles so their native methodologies remain available.",
        "files": ["product-judgement/SKILL.md"],
    },
}

# The complete collection as one file, for environments that accept a single
# upload. Product Judgement leads because it routes to the four local
# methodologies that follow it.
COMBINED = {
    "name": "all",
    "title": "Product Judgement—complete collection",
    "summary": "All five Skills in one file: Product Judgement plus the four foundational methodologies it calls—Focal, Compass, Flywheel, and Soul.",
    "order": ["product-judgement", "focal", "compass", "flywheel", "soul"],
}


def check_source_lists() -> None:
    """Fail if a Skill gained a reference file that no bundle would include."""
    for name, config in BUNDLES.items():
        discovered = [f"{name}/SKILL.md"] + sorted(
            str(path.relative_to(ROOT)) for path in (ROOT / name / "reference").rglob("*.md")
        )
        configured = list(config["files"])
        if sorted(configured) == sorted(discovered):
            continue

        missing = [path for path in discovered if path not in configured]
        unknown = [path for path in configured if path not in discovered]
        print(f"Bundle source list for {name} is incomplete.", file=sys.stderr)
        if missing:
            print(f"Missing: {', '.join(missing)}", file=sys.stderr)
        if unknown:
            print(f"Unknown: {', '.join(unknown)}", file=sys.stderr)
        sys.exit(2)


def combined_header() -> str:
    return (
        f"# {COMBINED['title']}\n"
        "\n"
        "> Generated by `python3 scripts/build_bundles.py` from the source files listed below. Do not edit this file directly.\n"
        "\n"
        f"{COMBINED['summary']}\n"
        "\n"
        "Load this single file when your environment accepts only one Markdown instruction or knowledge file and you want the holistic `/product-judgement` audit, which needs all four local methodologies present. Common uses include a ChatGPT Project or custom GPT knowledge file, a Claude Project, or a single rules file. If your agent supports multi-file Skills, install the Skill folders instead so references load on demand.\n"
        "\n"
        "---\n"
    )


def header(name: str, config: dict[str, object]) -> str:
    if name == "product-judgement":
        holistic_note = (
            "Product Judgement calls Focal, Compass, Flywheel, and Soul. In a single-file "
            "environment, load this file together with `focal.md`, `compass.md`, `flywheel.md`, and `soul.md`."
        )
    else:
        holistic_note = (
            f"If your agent supports multi-file Skills, install the `{name}/` folder instead so "
            "references can load on demand. Use this bundle when the environment accepts only one "
            "Markdown instruction file."
        )

    return (
        f"# {config['title']}—single-file bundle\n"
        "\n"
        "> Generated by `python3 scripts/build_bundles.py` from the source files listed below. Do not edit this file directly.\n"
        "\n"
        f"{config['summary']}\n"
        "\n"
        f"{holistic_note}\n"
        "\n"
        "Common uses include an instruction file, a rules file, or an uploaded knowledge file. The source sections are concatenated verbatim so the bundle cannot silently drift from the folder Skill.\n"
        "\n"
        "---\n"
    )


def source_section(relative_path: str) -> str:
    content = (ROOT / relative_path).read_text(encoding="utf-8").rstrip()
    return (
        f"## Source: `{relative_path}`\n"
        "\n"
        f"<!-- BEGIN GENERATED SOURCE: {relative_path} -->\n"
        "\n"
        f"{content}\n"
        "\n"
        f"<!-- END GENERATED SOURCE: {relative_path} -->\n"
    )


def render_bundle(name: str, config: dict[str, object]) -> str:
    sections = [source_section(path) for path in config["files"]]
    return "\n\n".join([header(name, config)] + sections).rstrip() + "\n"


def render_combined() -> str:
    sections = [
        source_section(path)
        for name in COMBINED["order"]
        for path in BUNDLES[name]["files"]
    ]
    return "\n\n".join([combined_header()] + sections).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if any(argument != "--check" for argument in argv):
        print("Usage: python3 scripts/build_bundles.py [--check]", file=sys.stderr)
        return 2

    check_source_lists()
    check_only = "--check" in argv

    outputs = [(name, render_bundle(name, config)) for name, config in BUNDLES.items()]
    outputs.append((COMBINED["name"], render_combined()))

    stale = []
    for name, expected in outputs:
        destination = ROOT / "bundles" / f"{name}.md"
        if check_only:
            if not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
                stale.append(destination)
        else:
            destination.write_text(expected, encoding="utf-8")
            print(f"generated {destination.relative_to(ROOT)}")

    if check_only and stale:
        print("Generated bundles are stale:", file=sys.stderr)
        for path in stale:
            print(f"- {path.relative_to(ROOT)}", file=sys.stderr)
        print("Run: python3 scripts/build_bundles.py", file=sys.stderr)
        return 1

    if check_only:
        print("All generated bundles are current.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
