#!/usr/bin/env ruby
# frozen_string_literal: true

ROOT = File.expand_path("..", __dir__)

BUNDLES = {
  "focal" => {
    title: "Focal",
    summary: "The complete Focal Skill, including its `/12` audit rubric, patterns, and worked examples.",
    files: [
      "focal/SKILL.md",
      "focal/reference/review.md",
      "focal/reference/patterns.md",
      "focal/reference/examples.md"
    ]
  },
  "compass" => {
    title: "Compass",
    summary: "The complete Compass Skill, including its `/12` audit rubric, patterns, and worked examples.",
    files: [
      "compass/SKILL.md",
      "compass/reference/review.md",
      "compass/reference/patterns.md",
      "compass/reference/examples.md"
    ]
  },
  "flywheel" => {
    title: "Flywheel",
    summary: "The complete Flywheel Skill, including its complete-evidence `/16` and targeted `/4` audit contracts, four play references, and worked examples.",
    files: [
      "flywheel/SKILL.md",
      "flywheel/reference/review.md",
      "flywheel/reference/trust.md",
      "flywheel/reference/friction.md",
      "flywheel/reference/wins.md",
      "flywheel/reference/emotion.md",
      "flywheel/reference/examples.md"
    ]
  },
  "soul" => {
    title: "Soul",
    summary: "The complete Soul Skill, including its unscored Readiness check, `/12` audit rubric, moment and treatment references, and worked examples.",
    files: [
      "soul/SKILL.md",
      "soul/reference/review.md",
      "soul/reference/moments.md",
      "soul/reference/treatments.md",
      "soul/reference/examples.md"
    ]
  },
  "product-judgement" => {
    title: "Product Judgement",
    summary: "The Product Judgement orchestration Skill. For a holistic audit, load it with the four foundational bundles so their native methodologies remain available.",
    files: ["product-judgement/SKILL.md"]
  }
}.freeze

# The complete collection as one file, for environments that accept a single
# upload. Product Judgement leads because it routes to the four local
# methodologies that follow it.
COMBINED = {
  name: "all",
  title: "Product Judgement—complete collection",
  summary: "All five Skills in one file: Product Judgement plus the four foundational methodologies it calls—Focal, Compass, Flywheel, and Soul.",
  order: %w[product-judgement focal compass flywheel soul]
}.freeze

BUNDLES.each do |name, config|
  discovered = ["#{name}/SKILL.md"] + Dir.glob(File.join(ROOT, name, "reference", "**", "*.md")).sort.map do |path|
    path.delete_prefix("#{ROOT}/")
  end
  # Mode-specific references are bundled even though folder installs load them on demand.
  config[:files] += discovered - config.fetch(:files)
  configured = config.fetch(:files)
  next if configured.sort == discovered.sort

  missing = discovered - configured
  unknown = configured - discovered
  warn "Bundle source list for #{name} is incomplete."
  warn "Missing: #{missing.join(", ")}" unless missing.empty?
  warn "Unknown: #{unknown.join(", ")}" unless unknown.empty?
  exit 2
end

def combined_header
  <<~MARKDOWN
    # #{COMBINED.fetch(:title)}

    > Generated by `ruby scripts/build_bundles.rb` from the source files listed below. Do not edit this file directly.

    #{COMBINED.fetch(:summary)}

    Load this single file when your environment accepts only one Markdown instruction or knowledge file and you want the holistic `/product-judgement` audit, which needs all four local methodologies present. Common uses include a ChatGPT Project or custom GPT knowledge file, a Claude Project, or a single rules file. If your agent supports multi-file Skills, install the Skill folders instead so references load on demand.

    ---
  MARKDOWN
end

def header(name, config)
  holistic_note = if name == "product-judgement"
                    <<~TEXT
                      Product Judgement calls Focal, Compass, Flywheel, and Soul. In a single-file environment, load this file together with `focal.md`, `compass.md`, `flywheel.md`, and `soul.md`.
                    TEXT
                  else
                    <<~TEXT
                      If your agent supports multi-file Skills, install the `#{name}/` folder instead so references can load on demand. Use this bundle when the environment accepts only one Markdown instruction file.
                    TEXT
                  end

  <<~MARKDOWN
    # #{config.fetch(:title)}—single-file bundle

    > Generated by `ruby scripts/build_bundles.rb` from the source files listed below. Do not edit this file directly.

    #{config.fetch(:summary)}

    #{holistic_note.strip}

    Common uses include an instruction file, a rules file, or an uploaded knowledge file. Source instructions are generated from the folder Skill. Relative links become links to included source sections (or repository sources when absent); identical shared contracts appear once per bundle.

    ---
  MARKDOWN
end

def source_anchor(path)
  "source-" + path.downcase.gsub(/[^a-z0-9]+/, "-").sub(/-+\z/, "")
end

def source_section(relative_path, included, shared_seen)
  absolute_path = File.join(ROOT, relative_path)
  content = File.read(absolute_path, encoding: "UTF-8").rstrip
  content = content.gsub(/<!-- BEGIN SHARED: ([a-z-]+) -->\n.*?\n<!-- END SHARED: \1 -->/m) do |fragment|
    name = Regexp.last_match(1)
    if shared_seen.include?(name)
      "See the [shared #{name} contract](#shared-#{name}) already included above."
    else
      shared_seen << name
      "<a id=\"shared-#{name}\"></a>\n\n#{fragment}"
    end
  end
  content = content.gsub(/\[([^\]]+)\]\(([^)]+)\)/) do |link|
    label = Regexp.last_match(1)
    target = Regexp.last_match(2)
    repository_prefix = "https://github.com/kvncnls/product-judgement/blob/main/"
    if target.start_with?(repository_prefix)
      source = target.delete_prefix(repository_prefix).split("#", 2).first
      next "[#{label}](##{source_anchor(source)})" if included.include?(source)
    end
    next link if target.start_with?("#", "/") || target.match?(/\A[a-z][a-z0-9+.-]*:/i)

    file, fragment = target.split("#", 2)
    resolved = File.expand_path(file, File.dirname(absolute_path))
    next link unless resolved.start_with?(ROOT + "/") || resolved == ROOT
    resolved = File.join(resolved, "SKILL.md") if File.directory?(resolved) && File.file?(File.join(resolved, "SKILL.md"))
    source = resolved.delete_prefix(ROOT + "/")
    if included.include?(source)
      "[#{label}](##{source_anchor(source)})"
    else
      suffix = fragment ? "##{fragment}" : ""
      "[#{label}](https://github.com/kvncnls/product-judgement/blob/main/#{source}#{suffix})"
    end
  end

  <<~MARKDOWN
    <a id="#{source_anchor(relative_path)}"></a>

    ## Source: `#{relative_path}`

    <!-- BEGIN GENERATED SOURCE: #{relative_path} -->

    #{content}

    <!-- END GENERATED SOURCE: #{relative_path} -->
  MARKDOWN
end

def render_sources(files)
  shared_seen = []
  files.map { |path| source_section(path, files, shared_seen) }
end

def render_bundle(name, config)
  ([header(name, config)] + render_sources(config.fetch(:files))).join("\n\n").rstrip + "\n"
end

def render_combined
  files = COMBINED.fetch(:order).flat_map { |name| BUNDLES.fetch(name).fetch(:files) }
  ([combined_header] + render_sources(files)).join("\n\n").rstrip + "\n"
end

if ARGV.any? { |argument| argument != "--check" }
  warn "Usage: ruby scripts/build_bundles.rb [--check]"
  exit 2
end

check_only = ARGV.include?("--check")
stale = []

outputs = BUNDLES.map { |name, config| [name, render_bundle(name, config)] }
outputs << [COMBINED.fetch(:name), render_combined]

outputs.each do |name, expected|
  ids = expected.scan(/<a id="([^"]+)"><\/a>/).flatten
  references = expected.scan(/\]\(#((?:source|shared)-[^)]+)\)/).flatten
  abort "#{name}: missing generated link anchors" unless (references - ids).empty?
  abort "#{name}: duplicate generated anchors" unless ids.uniq == ids
  destination = File.join(ROOT, "bundles", "#{name}.md")

  if check_only
    stale << destination unless File.file?(destination) && File.read(destination, encoding: "UTF-8") == expected
  else
    File.write(destination, expected, mode: "w", encoding: "UTF-8")
    puts "generated #{destination.delete_prefix("#{ROOT}/")}"
  end
end

if check_only && stale.any?
  warn "Generated bundles are stale:"
  stale.each { |path| warn "- #{path.delete_prefix("#{ROOT}/")}" }
  warn "Run: ruby scripts/build_bundles.rb"
  exit 1
end

puts "All generated bundles are current." if check_only
